### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [melisgl/micmac#1]
Building with SBCL 2.2.1 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id aa371af4465dc9acc7b6599d056b46268f2acccb

*micmac* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Package ALEXANDRIA does not exist. Line: 221, Column: 23, File-Position: 10859 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/micmac/e82a83a0449a03db7df0302f2fbc9b74fa81f83d/micmac-20220215-git/src/graph-search.lisp" {100680A713}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001B98003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "micmac" "src" "graph-search">

```

*micmac/test* fails to build because of a failure in  _micmac_.

[Full log here](http://report.quicklisp.org/2022-02-15/failure-report/micmac.html)

**Comment by melisgl** [comment]
That's what I get for only testing under Slime. Fixed in 33993da530b48b475808c04d95d552b33ae57d04.
